### ISSUE TITLE
mPresenter is null in onStart

### ISSUE THREAD

**Issue by biovolt** [benoitletondor/Android-Studio-MVP-template#8] opened 2017-04-18 06:22 UTC
Hi
Thank you for your awesome contribution!!

We have a couple of activities where we get crash reports of the mPresenter being null in the onStart.

We cannot reproduce the crash but we get it in the logs

Any ideas why ? 

`    @Override
    public void onStart() {
        super.onStart();
        if (mFirstStart) {
            mPresenter.setStartIndex(mStartIndex);
            mPresenter.performSearch();
            mFirstStart = false;
        }
    }`

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc.def/com.abc.view.impl.PhoneSearchResultsActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.abc.presenter.ISearchResultsPresenter.setStartIndex(int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.abc.presenter.ISearchResultsPresenter.setStartIndex(int)' on a null object reference
       at com.abc.view.impl.SearchResultsFragment.onStart(SearchResultsFragment.java:85)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2907)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:613)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.abc.view.impl.BaseActivity.onStart(BaseActivity.java:50)
       at com.abc.view.impl.PhoneSearchResultsActivity.onStart(PhoneSearchResultsActivity.java:81)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by benoitletondor** [comment] 2017-04-18 09:13
Hi @biovolt.

The crashes you get are totally normal. Depending on the runtime, it's totally possible that the presenter isn't ready when `Activity.onStart()` is reach.

If you look at the source code, it's totally handled by the template: https://github.com/benoitletondor/Android-Studio-MVP-template/blob/master/MVPBoilerplate/root/src/app_package/classes/BaseActivity.java.ftl#L54

I think you have this issue here cause you got something wrong: you put some logic into your Activity instead of your presenter. The code you have here in your Activity should be in the `onStart` method of your **presenter**, not your activity. 
The very concept of MVP is that your views should be as simple and dumb as possible, and all the logic is into your presenter. I would advice to move everything not UI related out of the Activity and bind your code to your Presenter lifecycle, which offer guarantees about `mView` being available when `onStart` is reach.

I'm closing this issue since it's the expected behaviour but feel free to ask questions if it's not clear for you.

Best

**Closed as completed by benoitletondor** 2017-04-18 09:13 UTC

**Comment by biovolt** [comment] 2017-04-24 09:31
I think I understand, thank you

Please let me know if this is right.

instead of calling my own init/setup method on the presenter from in my activity.onStart
i need to wait for the presenter.onStart and setup the views from there ?

**Comment by benoitletondor** [comment] 2017-04-24 09:32
That's exactly how MVP works indeed: Every decision is made by the presenter, and the view is just called by the presenter to update it.
